---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
```

```{r}
outdir <- "/Volumes/SciDrive/Archive/SCC/1_sandbox/20210805_HealthyVSTumourAnalysis/5_Figure2/a_AllCancerVSAllNormal/GenesOfInterest/outdir/"
#df <- readRDS("/Volumes/GML001-Q1851/Laura/SCC/0_data/SlimSCC_removeScale.RDS") #the same thing but on RDM, slimmed to remove scale data
df <- readRDS("/Volumes/SciDrive/Archive/SCC/0_data/SlimSCC_removeScale_NormalisedRNAAssay.RDS") #the same thing but on HD (quicker to load)

DE <- read.delim("/Volumes/SciDrive/Archive/SCC/1_sandbox/20210805_HealthyVSTumourAnalysis/1_CellTypesCombined/a_MarkerGenes/outdir/allcells_healthVStumour_top10.txt")

Idents(df) <- "pre"
DefaultAssay(df) <- "RNA"
```

```{r}
# DimPlot(df, group.by = "pre")
# DimPlot(df, group.by = "pre", split.by = "orig_ident")
# DimPlot(df, group.by = "pre", split.by = "type_ident")
```

# Plot 1: Normal vs Cancer UMAP

```{r}
palette_cancer <- c(`Cancer` = "deeppink3",
                    `Normal` = "turquoise3")
DimPlot(df, group.by = "orig_ident", cols = palette_cancer)
```
save the plot

```{r}
DimPlot(df, cols = palette_cancer, group.by = "orig_ident", pt.size = 0.05) +
    coord_fixed() + NoLegend()
ggsave(filename = paste0(outdir, "ClusterPlot_CancerVSNormal_noLegend.pdf"), width = 3, height = 3)

DimPlot(df, cols = palette_cancer, group.by = "orig_ident", pt.size = 0.01) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_blank()) +
    coord_fixed() + NoLegend()
ggsave(filename = paste0(outdir, "ClusterPlot_CancerVSNormal_noText.pdf"), width = 3, height = 3)

DimPlot(df, cols = palette_cancer, group.by = "orig_ident", pt.size = 0.05) +
    coord_fixed()
ggsave(filename = paste0(outdir, "ClusterPlot_CancerVSNormal_wLegend.pdf.pdf"), width = 3, height = 3)
```

```{r}
DimPlot(df, cols = palette_cancer, group.by = "orig_ident", pt.size = 0.0000001) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_blank()) +
    coord_fixed() + NoLegend()
ggsave(filename = paste0(outdir, "ClusterPlot_CancerVSNormal_noText_smlPts.pdf"), width = 7, height = 7)
```


# Plot expression of top cancer and normal genes

```{r}
cancer_genes <- DE %>% filter(cluster == "Cancer") %>% pull(gene)
normal_genes <- DE %>% filter(cluster == "Normal") %>% pull(gene)
```

```{r}
Idents(df) <- "orig_ident"

for (gene in cancer_genes) {
  data_exp <- FeaturePlot(df, order = TRUE, features = gene, pt.size = 0.1)
  data_exp <- data_exp$data 
  colnames(data_exp) <- c("UMAP_1", "UMAP_2", "ident", "myGene")
  myplot2 <- ggplot(data_exp, aes(x = UMAP_1, y = UMAP_2, color = myGene)) +
  ggplot2::scale_color_gradientn(colours = c("grey80", "yellow", "orange", "red")) +
  geom_point(size = 0.1) +
  facet_grid(. ~ ident) +
  coord_fixed() +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_blank())
  ggsave(plot = myplot2, filename = paste0(outdir, "CancerGenes_", gene, ".pdf"), width = 6, height = 3)
}


for (gene in normal_genes) {
  data_exp <- FeaturePlot(df, order = TRUE, features = gene, pt.size = 0.1)
  data_exp <- data_exp$data 
  colnames(data_exp) <- c("UMAP_1", "UMAP_2", "ident", "myGene")
  myplot2 <- ggplot(data_exp, aes(x = UMAP_1, y = UMAP_2, color = myGene)) +
  ggplot2::scale_color_gradientn(colours = c("grey80", "yellow", "orange", "red")) +
  geom_point(size = 0.1) +
  facet_grid(. ~ ident) +
  coord_fixed() +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title = element_blank())
  ggsave(plot = myplot2, filename = paste0(outdir, "NormalGenes_", gene, ".pdf"), width = 6, height = 3)
}

Idents(df) <- "pre"
```



```{r}
0.0000001
```

