---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
```

```{r}
outdir <- "/path/to/outdir/"
df <- readRDS("/path/to/SlimSCC_removeScale_NormalisedRNAAssay.RDS") #the same thing but on HD (quicker to load)
Idents(df) <- "pre"
DefaultAssay(df) <- "RNA"
```

# make patient codes only

```{r}
meta <- df[[c("sample_ident", "sample_ident")]]
colnames(meta) <- c("sample_ident", "patient")
meta$patient <- gsub("_.*", "", meta$patient)
write.table(meta, file = paste0(outdir, "patientID.txt"), sep = "\t", quote = FALSE, col.names = NA)
df <- AddMetaData(df, meta[,"patient",drop = FALSE])
```

```{r}
DimPlot(df, group.by = "patient")
```

# Analysis 1: all cells, healthy vs. tumour

```{r}
Idents(df) <- "orig_ident"

for (cluster in unique(df$patient)) {
  cells <- names(which(df$patient == cluster))
  # only run if multiple subtypes
  if (length(unique(df[[]][cells, "orig_ident"])) > 1) {
    df_subset <- subset(df, cells = cells)
    markers <- FindAllMarkers(df_subset, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
    if (length(markers$gene) > 0) {
        sig_markers <- markers %>%
      filter(p_val_adj <= 0.05)
    
    top10 <- markers %>%
      filter(p_val_adj <= 0.05) %>%
      group_by(cluster) %>%
      arrange(-(avg_log2FC)) %>%
      dplyr::slice(1:10, with_ties = FALSE)

    top100 <- markers %>% filter(p_val_adj <= 0.05) %>%
      group_by(cluster) %>%
      arrange(-(avg_log2FC)) %>%
      dplyr::slice(1:100, with_ties = FALSE)

write.table(sig_markers, file = paste0(outdir, "patientwise_healthVStumour_SigMarkers_patient_", cluster, ".txt"), sep = "\t", quote = FALSE, col.names = NA)

write.table(top10, file = paste0(outdir, "patientwise_healthVStumour_Top10_patient_", cluster, ".txt"), sep = "\t", quote = FALSE, col.names = NA)

write.table(top100, file = paste0(outdir, "patientwise_healthVStumour_Top100_patient_", cluster, ".txt"), sep = "\t", quote = FALSE, col.names = NA)    
    #df_subset <- ScaleData(df_subset, features = top10$gene)
    if (length(top10$gene) > 0) {
    DotPlot(df_subset, features = top10$gene) + RotatedAxis()
    ggsave(filename = paste0(outdir, "patientwise_healthVStumour_top10_patient_", cluster, ".jpeg"))
    }
    }
    } else {
      print("no cells in one condition!")
      }
}
```


