---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
# load packages
library(clusterProfiler)
library(dplyr)
library(org.Hs.eg.db)
library(ggplot2)
library(ComplexHeatmap)
library(stringr)
library(enrichplot)
```

```{r}
outdir <- "/path/to/outdir_GO_binary/"

sampleID <- "binary"

all <- read.delim("/path/to/allmarkers_binaryGroups.txt")

universe <- read.delim("/path/to/universe.txt")
```

# split "all" into up and downregulated

```{r}
all <- mutate(all, dir = ifelse(avg_log2FC > 0, "up", "down"))
all <- mutate(all, sample_dir = paste0(cancer, "_", dir))
```


```{r}
universe <- universe$universe_genes
universe_entrez <- mapIds(org.Hs.eg.db, keys=universe, column="ENTREZID", keytype="SYMBOL")
universe_entrez <- universe_entrez[!(is.na(universe_entrez))]

# Get Entrez codes for DE gene
# first remove genes that aren't in valid hits, because if they're the only genes for one list it fails
# Get Entrez codes for DE gene
# first remove genes that aren't in valid hits, because if they're the only genes for one list it fails
DE <- all # just for the nomenclature of the code
DE <- all[DE$X %in% names(universe_entrez),]

prep_IDs <- function(list_to_test) {
  geneList <- pull(DE %>% dplyr::filter(sample_dir == list_to_test), "X")
  myIDs = mapIds(org.Hs.eg.db, column = "ENTREZID", keytype = "SYMBOL", keys = geneList)
  myIDs = myIDs[!(is.na(myIDs))]
  return(myIDs)
}
all_entrez <- lapply(unique(DE$sample_dir), prep_IDs)
names(all_entrez) <- unique(DE$sample_dir)
```

```{r}
ck <- compareCluster(geneCluster = all_entrez, fun = "enrichGO", OrgDb = "org.Hs.eg.db", universe = universe_entrez, readable = TRUE, ont = "BP", pvalueCutoff = 0.01, pAdjustMethod = "BH")
ck_filt <- gsfilter(ck, max = 200)
ck_filt_simple <- clusterProfiler::simplify(ck_filt, cutoff = 0.5)

# save output as RDS, txt file, simple dotplot
## RDS
saveRDS(ck_filt_simple, paste0(outdir, sampleID, "_GOFiltSimp.RDS"))
## txt file
tosave <- ck_filt_simple@compareClusterResult
tosave$GeneRatio <- gsub("\\/", "|", tosave$GeneRatio)
tosave$BgRatio <- gsub("\\/", "|", tosave$BgRatio)
write.table(tosave, file = paste0(outdir, sampleID, "_top100GO_FiltSimp.txt"), sep = "\t", quote = FALSE, col.names = NA)
## dotplot
pdf(paste0(outdir, sampleID, "_ClusterMarker_dotplot.pdf"))
dotplot(ck_filt_simple, font.size = 8, showCategory = 7)
dev.off()
```

```{r}
## dotplot
pdf(paste0(outdir, sampleID, "_CoreGenes_dotplot.pdf"), width = 15)
dotplot(ck_filt_simple, font.size = 8, showCategory = 10)
dev.off()

## networkplot
pdf(paste0(outdir, sampleID, "_CoreGenes_networkplot.pdf"), width = 15)
cnetplot(ck_filt_simple, showCategory = 10, node_label = "category")
dev.off()


## networkplot 2
pdf(paste0(outdir, sampleID, "_CoreGenes_networkplotv2.pdf"), width = 15)
emapplot(pairwise_termsim(ck_filt_simple))
dev.off()
```

```{r}
n <- 5
myWidth <- 5
myHeight <- 5

  topN <- ck_filt_simple@compareClusterResult %>%
    group_by(Cluster) %>%
    arrange(p.adjust) %>%
    dplyr::slice(1:n, with_ties = FALSE)
  topN <- mutate(topN, ID_desc = paste0(ID, ": ", Description))

  topNuniq <- unique(topN$Description)
  topNuniq_IDdesc <- unique(topN$ID_desc)
  
  topN_allhits <- ck_filt_simple@compareClusterResult[which(ck_filt_simple@compareClusterResult$Description %in% topNuniq),]
  
  # prepare the data table
  table <- topN_allhits[,c(1,2,3,4,5,7)]
  
  # add in the various ratios to control dot size
  table <- tidyr::separate(data = table, col = GeneRatio, into = c("k_GOIinSet", "n_GOI"), sep = "\\/")
  table <- tidyr::separate(data = table, col = BgRatio, into = c("M_Set", "N_background"), sep = "\\/")
  ## make numeric
  table$k_GOIinSet <- as.numeric(table$k_GOIinSet)
  table$n_GOI <- as.numeric(table$n_GOI)
  table$M_Set <- as.numeric(table$M_Set)
  table$N_background <- as.numeric(table$N_background)  
  ## make a ratio
  table <- mutate(table, GeneRatio = k_GOIinSet / n_GOI)
  table <- mutate(table, Ratio_kM = k_GOIinSet / M_Set)
  
  # for the sake of visualisation, convert p-values to log10 and invert the numbers of the downregulated hits
  table <- mutate(table, padjdir = -log10(p.adjust + 1e-6))
  
  # simplify the "traj_0_" cluster names to just the number to aid with the ordering/legend
  #table <- mutate(table, Path = as.numeric(word(Cluster, 2, sep = "_")))
  #table$Path <- as.factor(table$Path) # convert to factor data type
  #levels(table$Path) <- sort(as.numeric(levels(table$Path)))
  
  # work out which gene to plot and order them by path ID
  markers <- table$Description %>% unique()
  table$Description <- factor(table$Description, levels = rev(topNuniq))
  
  table <- mutate(table, ID_desc = paste0(ID, ": ", Description))
  
  table$Description <- factor(table$Description, levels = rev(topNuniq))
  table$ID_desc <- factor(table$ID_desc, levels = rev(topNuniq_IDdesc))
  
  # generate the plots
  ## size is gene ratio, colour is up/downreg - this is the best one
  dotplot_grp_topN <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = Description, color = padjdir, size = GeneRatio)) + 
    geom_point(aes(fill=padjdir), colour="grey50",pch=21) +
    scale_fill_gradientn(colours = c("white", "gold", "orange", "red"),
                         values = scales::rescale(c(0, max(table$padjdir)/3, (max(table$padjdir)/3)*2, max(table$padjdir)))) +
    scale_y_discrete(position = "right", labels = function(x) stringr::str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
    pdf(paste0(outdir, "dotplot_generatio+p_val_adj.pdf"), width = myWidth, height = myHeight)
    #labels + dotplot_grp + plot_layout(ncol = 1, heights = c(0.9, 20))
    print(dotplot_grp_topN)
    dev.off()
    
    ## same as above but include the GO ID in the name
    dotplot_grp_topN_withGOLabels <- table %>% filter(Description %in% markers) %>% 
      ggplot(aes(x=Cluster, y = ID_desc, color = padjdir, size = GeneRatio)) + 
      geom_point(aes(fill=padjdir), colour="grey50",pch=21) +
      scale_fill_gradientn(colours = c("white", "gold", "orange", "red"),
                           values = scales::rescale(c(0, max(table$padjdir)/3, (max(table$padjdir)/3)*2, max(table$padjdir)))) +
      scale_y_discrete(position = "right", labels = function(x) stringr::str_trunc(x, width = 80, side = "center")) +
      theme_light(base_size = 10) +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
    
    pdf(paste0(outdir, "dotplot_generatio+p_val_adj_WithGOLabels.pdf"), width = (myWidth + 1), height = (myHeight + 0.5)) #extra width to allow for GO ID; idk why height varies
    #labels + dotplot_grp + plot_layout(ncol = 1, heights = c(0.9, 20))
    print(dotplot_grp_topN_withGOLabels)
    dev.off()
```

```{r}
# ------------------------------------------------------------------
# DO SOME FILTERING TO GET THE MOST SPECIFIC/UNIQUE TERMS
# ------------------------------------------------------------------

GOhits <- ck_filt_simple@compareClusterResult
singlets_ID <- names(which(table(GOhits$ID) == 1))
GOhits_singlets <- GOhits[GOhits$ID %in% singlets_ID,]
```

```{r}
n <- 5
myWidth <- 7
myHeight <- 5

# add in "ID_desc" column
GOhits_singlets <- mutate(GOhits_singlets, ID_desc = paste0(ID, ": ", Description))
GOhits_singlets$Cluster <- as.factor(GOhits_singlets$Cluster) # convert to factor data type
  
  # get the top N of each group
  topN <- GOhits_singlets %>%
    group_by(Cluster) %>%
    arrange(p.adjust) %>%
    dplyr::slice(1:n)
  topNuniq <- unique(topN$Description)
  topN_allhits <- GOhits_singlets[which(GOhits_singlets$Description %in% topNuniq),]
  
  # prepare the data table
  table <- topN_allhits[,c(1,3,4,5,7,11)]
  
  # add in the various ratios to control dot size
  table <- tidyr::separate(data = table, col = GeneRatio, into = c("k_GOIinSet", "n_GOI"), sep = "\\/")
  table <- tidyr::separate(data = table, col = BgRatio, into = c("M_Set", "N_background"), sep = "\\/")
  ## make numeric
  table$k_GOIinSet <- as.numeric(table$k_GOIinSet)
  table$n_GOI <- as.numeric(table$n_GOI)
  table$M_Set <- as.numeric(table$M_Set)
  table$N_background <- as.numeric(table$N_background)  
  ## make a ratio
  table <- mutate(table, GeneRatio = k_GOIinSet / n_GOI)
  table <- mutate(table, Ratio_kM = k_GOIinSet / M_Set)
  
  # for the sake of visualisation, convert p-values to log10
  table <- mutate(table, logpadj = -log10(p.adjust + 1e-6))

 
   # work out which genes to plot and order them by path ID
  markers <- table$Description %>% unique()
  table$Description <- factor(table$Description, levels = rev(topNuniq))
  
  # add in the GO term to the name, optionally
  markers_IDdesc <- table$ID_desc %>% unique()
  topNuniq_IDdesc <- unique(topN$ID_desc)
  table$ID_desc <- factor(table$ID_desc, levels = rev(topNuniq_IDdesc))
  
  ## size is gene ratio, colour is up/downreg - this is the best one
  dotplot_grp_topN <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = Description, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_uniqueHits_dotplot.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN)
  dev.off()
  
  ## the same plot, but show the GO term names
  dotplot_grp_topN_withGOlabels <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = ID_desc, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_uniqueHits_dotplot_withGOlabels.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN_withGOlabels)
  dev.off()
```


```{r}
n <- 3
myWidth <- 7
myHeight <- 2.7

# add in "ID_desc" column
GOhits_singlets <- mutate(GOhits_singlets, ID_desc = paste0(ID, ": ", Description))
GOhits_singlets$Cluster <- as.factor(GOhits_singlets$Cluster) # convert to factor data type
  
  # get the top N of each group
  topN <- GOhits_singlets %>%
    group_by(Cluster) %>%
    arrange(p.adjust) %>%
    dplyr::slice(1:n)
  topNuniq <- unique(topN$Description)
  topN_allhits <- GOhits_singlets[which(GOhits_singlets$Description %in% topNuniq),]
  
  # prepare the data table
  table <- topN_allhits[,c(1,3,4,5,7,11)]
  
  # add in the various ratios to control dot size
  table <- tidyr::separate(data = table, col = GeneRatio, into = c("k_GOIinSet", "n_GOI"), sep = "\\/")
  table <- tidyr::separate(data = table, col = BgRatio, into = c("M_Set", "N_background"), sep = "\\/")
  ## make numeric
  table$k_GOIinSet <- as.numeric(table$k_GOIinSet)
  table$n_GOI <- as.numeric(table$n_GOI)
  table$M_Set <- as.numeric(table$M_Set)
  table$N_background <- as.numeric(table$N_background)  
  ## make a ratio
  table <- mutate(table, GeneRatio = k_GOIinSet / n_GOI)
  table <- mutate(table, Ratio_kM = k_GOIinSet / M_Set)
  
  # for the sake of visualisation, convert p-values to log10
  table <- mutate(table, logpadj = -log10(p.adjust + 1e-6))

 
   # work out which genes to plot and order them by path ID
  markers <- table$Description %>% unique()
  table$Description <- factor(table$Description, levels = rev(topNuniq))
  
  # add in the GO term to the name, optionally
  markers_IDdesc <- table$ID_desc %>% unique()
  topNuniq_IDdesc <- unique(topN$ID_desc)
  table$ID_desc <- factor(table$ID_desc, levels = rev(topNuniq_IDdesc))
  
  ## size is gene ratio, colour is up/downreg - this is the best one
  dotplot_grp_topN <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = Description, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_", n, "uniqueHits_dotplot.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN)
  dev.off()
  
  ## the same plot, but show the GO term names
  dotplot_grp_topN_withGOlabels <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = ID_desc, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_", n, "uniqueHits_dotplot_withGOlabels.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN_withGOlabels)
  dev.off()
```


```{r}
n <- 3
myWidth <- 6.3
myHeight <- 2.9

# add in "ID_desc" column
GOhits_singlets <- mutate(GOhits_singlets, ID_desc = paste0(ID, ": ", Description))
GOhits_singlets$Cluster <- as.factor(GOhits_singlets$Cluster) # convert to factor data type
  
  # get the top N of each group
  topN <- GOhits_singlets %>%
    group_by(Cluster) %>%
    arrange(p.adjust) %>%
    dplyr::slice(1:n)
  topNuniq <- unique(topN$Description)
  topN_allhits <- GOhits_singlets[which(GOhits_singlets$Description %in% topNuniq),]
  
  # prepare the data table
  table <- topN_allhits[,c(1,3,4,5,7,11)]
  
  # add in the various ratios to control dot size
  table <- tidyr::separate(data = table, col = GeneRatio, into = c("k_GOIinSet", "n_GOI"), sep = "\\/")
  table <- tidyr::separate(data = table, col = BgRatio, into = c("M_Set", "N_background"), sep = "\\/")
  ## make numeric
  table$k_GOIinSet <- as.numeric(table$k_GOIinSet)
  table$n_GOI <- as.numeric(table$n_GOI)
  table$M_Set <- as.numeric(table$M_Set)
  table$N_background <- as.numeric(table$N_background)  
  ## make a ratio
  table <- mutate(table, GeneRatio = k_GOIinSet / n_GOI)
  table <- mutate(table, Ratio_kM = k_GOIinSet / M_Set)
  
  # for the sake of visualisation, convert p-values to log10
  table <- mutate(table, logpadj = -log10(p.adjust + 1e-6))

 
   # work out which genes to plot and order them by path ID
  markers <- table$Description %>% unique()
  table$Description <- factor(table$Description, levels = rev(topNuniq))
  
  # add in the GO term to the name, optionally
  markers_IDdesc <- table$ID_desc %>% unique()
  topNuniq_IDdesc <- unique(topN$ID_desc)
  table$ID_desc <- factor(table$ID_desc, levels = rev(topNuniq_IDdesc))
  
  ## size is gene ratio, colour is up/downreg - this is the best one
  dotplot_grp_topN <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = Description, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_", n, "uniqueHits_dotplot2.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN)
  dev.off()
  
  ## the same plot, but show the GO term names
  dotplot_grp_topN_withGOlabels <- table %>% filter(Description %in% markers) %>% 
    ggplot(aes(x=Cluster, y = ID_desc, color = logpadj, size = GeneRatio)) + 
    geom_point() +
    scale_size_continuous(range = c(0.5, 4)) +
    scale_color_gradientn(colours = c("yellow", "orange", "red"),
                          values = scales::rescale(c(0, max(table$logpadj)/2, max(table$logpadj)))) +
    scale_y_discrete(position = "right", labels = function(x) str_trunc(x, width = 80, side = "center")) +
    theme_light(base_size = 10)
  
  pdf(paste0(outdir, sampleID, "_", n, "uniqueHits_dotplot_withGOlabels2.pdf"), width = myWidth, height = myHeight)
  print(dotplot_grp_topN_withGOlabels)
  dev.off()
```