---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ComplexHeatmap)
library(ggplot2)
library(dplyr)
library(Seurat)
```

```{r}
outdir <- "/path/to/outdir/"

SCC_scores <- read.csv("/path/to/P30SCC_LR_score.csv", row.names = 1)
BCC_scores <- read.csv("/path/to/B18BCC_LR_score.csv", row.names = 1)
mel_scores <- read.csv("/path/to/Mela48974_LR_score.csv", row.names = 1)

BCC_seurat <- readRDS("/path/to/V32A_B18_BCC.rds")
mel_seurat <- readRDS("/path/to/V25A_48974_Mela.rds")
SCC_seurat <- readRDS("/path/to/V32B_P30_SCC.rds")
```

# Plot the scores in the tissues

```{r}
# filter to genes of interest
SCC_scores <- SCC_scores[,"IL34_CSF1R", drop = FALSE]
BCC_scores <- BCC_scores[,"IL34_CSF1R", drop = FALSE]
mel_scores <- mel_scores[,"IL34_CSF1R", drop = FALSE]

# Add to metadata
SCC_seurat <- AddMetaData(SCC_seurat, SCC_scores)
BCC_seurat <- AddMetaData(BCC_seurat, BCC_scores)
mel_seurat <- AddMetaData(mel_seurat, mel_scores)
```

# Plot

## get plotting parameters

```{r}
coord_SCC <- GetTissueCoordinates(object = SCC_seurat)
coord_BCC <- GetTissueCoordinates(object = BCC_seurat)
coord_mel <- GetTissueCoordinates(object = mel_seurat)

ratio_SCC <- (max(coord_SCC$imagerow) - min(coord_SCC$imagerow)) / (max(coord_SCC$imagecol) - min(coord_SCC$imagecol))
ratio_BCC <- (max(coord_BCC$imagerow) - min(coord_BCC$imagerow)) / (max(coord_BCC$imagecol) - min(coord_BCC$imagecol))
ratio_mel <- (max(coord_mel$imagerow) - min(coord_mel$imagerow)) / (max(coord_mel$imagecol) - min(coord_mel$imagecol))

SpatialDimPlot(SCC_seurat, pt.size.factor = 1.3) + NoLegend() +
  theme(aspect.ratio = ratio_SCC)
SpatialDimPlot(BCC_seurat, pt.size.factor = 1.4) + NoLegend() +
  theme(aspect.ratio = ratio_BCC)
SpatialDimPlot(mel_seurat, pt.size.factor = 1.3) + NoLegend() +
  theme(aspect.ratio = ratio_mel)

dot_SCC <- 1.3
dot_BCC <- 1.4
dot_mel <- 1.3
```

```{r}
## get the scale for each gene
SCC_max <- data.frame(LR = colnames(SCC_scores),
                      max = matrixStats::colMaxs(as.matrix(SCC_scores[sapply(SCC_scores, is.numeric)])),
                      sample = rep("SCC", length(colnames(SCC_scores))))
BCC_max <- data.frame(LR = colnames(BCC_scores),
                      max = matrixStats::colMaxs(as.matrix(BCC_scores[sapply(BCC_scores, is.numeric)])),
                      sample = rep("BCC", length(colnames(BCC_scores))))
mel_max <- data.frame(LR = colnames(mel_scores),
                      max = matrixStats::colMaxs(as.matrix(mel_scores[sapply(mel_scores, is.numeric)])),
                      sample = rep("mel", length(colnames(mel_scores))))
mymax <- rbind(SCC_max, BCC_max, mel_max)
mymax <- as.data.frame(tidyr::spread(mymax, key = LR, value = max))
mymax[is.na(mymax)] <- 0
rownames(mymax) <- mymax$sample
mymax$sample <- NULL

# now get the overall max
scalemax <- data.frame(LR = colnames(mymax),
                      max = matrixStats::colMaxs(as.matrix(mymax[sapply(mymax, is.numeric)])))
rownames(scalemax) <- scalemax$LR
```



```{r}
#dir.create(file.path(outdir, "SCC"), showWarnings = FALSE)
#dir.create(file.path(outdir, "BCC"), showWarnings = FALSE)
#dir.create(file.path(outdir, "mel"), showWarnings = FALSE)
#dir.create(file.path(outdir, "all"), showWarnings = FALSE)

for (i in colnames(SCC_scores)) {
  maxval <- scalemax[i,"max"]
  minval <- maxval/4
  SpatialFeaturePlot(SCC_seurat, features = i, pt.size.factor = dot_SCC) +
    theme(aspect.ratio = ratio_SCC) +
    ggplot2::scale_fill_gradientn(limits = c(0, maxval), breaks = c(0, maxval/4, maxval/2, (maxval/4)*3, maxval), colours = c("grey80", "gold", "orange", "red", "brown"))
  ggsave(filename = paste0(outdir, i, "_SCC", ".pdf"), width = 5)
}

for (i in colnames(BCC_scores)) {
  maxval <- scalemax[i,"max"]
  minval <- maxval/4
  SpatialFeaturePlot(BCC_seurat, features = i, pt.size.factor = dot_BCC) +
    theme(aspect.ratio = ratio_BCC) +
    ggplot2::scale_fill_gradientn(limits = c(0, maxval), breaks = c(0, maxval/4, maxval/2, (maxval/4)*3, maxval), colours = c("grey80", "gold", "orange", "red", "brown"))
  ggsave(filename = paste0(outdir, i, "_BCC", ".pdf"), width = 5)
}

for (i in colnames(mel_scores)) {
  maxval <- scalemax[i,"max"]
  minval <- maxval/4
  SpatialFeaturePlot(mel_seurat, features = i, pt.size.factor = dot_mel) +
    theme(aspect.ratio = ratio_mel) +
    ggplot2::scale_fill_gradientn(limits = c(0, maxval), breaks = c(0, maxval/4, maxval/2, (maxval/4)*3, maxval), colours = c("grey80", "gold", "orange", "red", "brown"))
  ggsave(filename = paste0(outdir, i, "_mel", ".pdf"), width = 5)
}
```
